version: "3.8"

services:

  test_runner:
    container_name: "test_runner"
    build:
      context: .
      dockerfile: ./testrunner.Dockerfile
    tty: true
    restart: on-failure
    volumes:
      - ./test:/home/dimsuser/test

  test_activemq:
    container_name: "test_activemq"
    build:
      context: .
      dockerfile: ./activemq/activemq.Dockerfile
    restart: on-failure
    ports:
      - "8162:8161"
