version: "3.8"

services:

  dev_dims:
    container_name: "dev_dims"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: on-failure
    ports:
      - "10580:8443"
    volumes:
      - ./app:/home/dimsuser/app
      - ./logs:/home/dimsuser/logs

  dev_activemq:
    container_name: "dev_activemq"
    build:
      context: .
      dockerfile: ./activemq/activemq.Dockerfile
    restart: on-failure
    ports:
      - "8161:8161"
      - "61613:61613"
    volumes:
      - ./activemq/data:/opt/apache-activemq/data
