version: "3.8"

services:

  test_runner:
    container_name: "test_runner"
    build:
      context: .
      dockerfile: ./testrunner.Dockerfile
    tty: true
    restart: on-failure
    volumes:
      - ./app:/home/dimsuser/app
      - ./test:/home/dimsuser/test

  test_mongodb:
    container_name: "test_mongodb"
    image: "mongo:4.0.28"
    restart: on-failure
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  test_activemq:
    container_name: "test_activemq"
    build:
      context: .
      dockerfile: ./activemq/activemq.Dockerfile
    restart: on-failure
    ports:
      - "8162:8161"
