version: "3.8"

services:

  dev_dims:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "13880:5000"
    volumes:
      - ./app:/home/dimsuser/app

  dev_activemq:
    build:
      context: .
      dockerfile: ./activemq/Dockerfile
    restart: on-failure
    ports:
      - "8161:8161"
      - "61613:61613"
    volumes:
      - ./activemq/data:/opt/apache-activemq/data
