openapi: 3.0.3
info:
  title: DRS Import Managament Service API
  version: 0.1.0

paths:
  /ingest:
    post:
      operationId: initiateIngest
      summary: Initiates a new ingest
      responses:
        202:
          description: Ingest accepted and started processing
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                  - error
                properties:
                  data:
                    $ref: "#/components/schemas/IngestConfirmation"
                  error:
                    type: string
                    nullable: true
        500:
          $ref: "#/components/responses/InternalError"

components:
  schemas:
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            type: object
            required:
              - data
              - error
            properties:
              error:
                type: string
              data:
                type: object
                nullable: true
    IngestConfirmation:
      type: object
      required:
        - ingest_status
      properties:
        ingest_status:
          type: string
          description: Ingest status
